### ISSUE TITLE
serving on localhost:7531 ---------------------------------------- Exception happened during processing of request from ('127.0.0.1', 52654) Traceback (most recent call last):   File "C:\Program Files\py\lib\socketserver.py", line 317, in _handle_request_noblock     self.process_request(request, client_address)   File "C:\Program Files\py\lib\socketserver.py", line 348, in process_request     self.finish_request(request, client_address)   File "C:\Program Files\py\lib\socketserver.py", line 361, in finish_request     self.RequestHandlerClass(request, client_address, self)   File "C:\Program Files\py\lib\socketserver.py", line 696, in __init__     self.handle()   File "C:\Program Files\py\lib\http\server.py", line 418, in handle     self.handle_one_request()   File "C:\Program Files\py\lib\http\server.py", line 406, in handle_one_request     method()

### ISSUE THREAD

**Issue by dEN5-tech** [Thann/play-with-mpv#45]
![NxkVfxM5Wo](https://user-images.githubusercontent.com/54153548/104330650-3a832900-54ff-11eb-8c49-3eac595655b0.gif)

**Comment by AikoNation** [comment]
i'm having the exact same problem, had some issue getting pip to work but after i fixed that issue i'm now stuck

**Comment by Reinbowsaur** [comment]
Same here. On windows 10.

**Comment by Chaostheorie** [comment]
Related to #50 ?
