### ISSUE TITLE
Error on installing the server

### ISSUE THREAD

**Issue by parsanoori** [Thann/play-with-mpv#53]
Been running `pip3 install git+https://github.com/thann/play-with-mpv` but got the following output:

```
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_gn3hp6x/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_gn3hp6x/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8646fqve
         cwd: /tmp/pip-req-build-_gn3hp6x/
    Complete output (46 lines):
    WARNING: The wheel package is not available.
    WARNING: Skipping page https://github.com/thann/install_freedesktop/tarball/master#egg=install_freedesktop-0.2.0 because the GET request got Content-Type: application/x-gzip.The only supported Content-Type is text/html
      WARNING: Cache entry deserialization failed, entry ignored
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-r1x9agur/install-freedesktop_55051b358b2843a8832f8ed15439cfd7/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-r1x9agur/install-freedesktop_55051b358b2843a8832f8ed15439cfd7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-rorsue2t
           cwd: /tmp/pip-wheel-r1x9agur/install-freedesktop_55051b358b2843a8832f8ed15439cfd7/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for install-freedesktop
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp75ck894n', '--quiet', '--find-links', 'https://github.com/thann/install_freedesktop/tarball/master#egg=install_freedesktop-0.2.0', 'install_freedesktop>=0.2.0']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-_gn3hp6x/setup.py", line 27, in <module>
        setup(
      File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 780, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp75ck894n', '--quiet', '--find-links', 'https://github.com/thann/install_freedesktop/tarball/master#egg=install_freedesktop-0.2.0', 'install_freedesktop>=0.2.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by parsanoori** [comment]
Installed `wheel` manually.
