### ISSUE TITLE
Cannot install on Python 3.8.9 on Windows

### ISSUE THREAD

**Issue by ScribbleGhost** [Thann/play-with-mpv#58]
On python Python 3.8.9 I get the following error when running `pip install git+git://github.com/thann/play-with-mpv --user`.

```
D:\Dowanloads\play-with-mpv-master\play-with-mpv-master>pip install git+git://github.com/thann/play-with-mpv --user
Collecting git+git://github.com/thann/play-with-mpv
  Cloning git://github.com/thann/play-with-mpv to c:\users\John\appdata\local\temp\pip-req-build-ysqahxpn
  Running command git clone -q git://github.com/thann/play-with-mpv 'C:\Users\John\AppData\Local\Temp\pip-req-build-ysqahxpn'
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\John\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\John\\AppData\\Local\\Temp\\pip-req-build-ysqahxpn\\setup.py'"'"'; __file__='"'"'C:\\Users\\John\\AppData\\Local\\Temp\\pip-req-build-ysqahxpn\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\John\AppData\Local\Temp\pip-pip-egg-info-wcf18dbu'
         cwd: C:\Users\John\AppData\Local\Temp\pip-req-build-ysqahxpn\
    Complete output (46 lines):
    WARNING: The wheel package is not available.
    WARNING: Skipping page https://github.com/thann/install_freedesktop/tarball/master#egg=install_freedesktop-0.2.0 because the GET request got Content-Type: application/x-gzip.The only supported Content-Type is text/html
      WARNING: Cache entry deserialization failed, entry ignored
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\John\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\John\\AppData\\Local\\Temp\\pip-wheel-rlmm4zxc\\install-freedesktop_59089db6ec5a4b5d8ac463f92f5ddfdc\\setup.py'"'"'; __file__='"'"'C:\\Users\\John\\AppData\\Local\\Temp\\pip-wheel-rlmm4zxc\\install-freedesktop_59089db6ec5a4b5d8ac463f92f5ddfdc\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\John\AppData\Local\Temp\pip-wheel-nq__mfkx'
           cwd: C:\Users\John\AppData\Local\Temp\pip-wheel-rlmm4zxc\install-freedesktop_59089db6ec5a4b5d8ac463f92f5ddfdc\
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for install-freedesktop
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "c:\users\John\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "c:\users\John\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\users\\John\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\John\\AppData\\Local\\Temp\\tmpoi_65ss4', '--quiet', '--find-links', 'https://github.com/thann/install_freedesktop/tarball/master#egg=install_freedesktop-0.2.0', 'install_freedesktop>=0.2.0']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\John\AppData\Local\Temp\pip-req-build-ysqahxpn\setup.py", line 27, in <module>
        setup(
      File "c:\users\John\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "c:\users\John\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\John\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 779, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\users\John\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\users\John\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "c:\users\John\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1063, in obtain
        return installer(requirement)
      File "c:\users\John\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 838, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\users\John\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['c:\\users\\John\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\John\\AppData\\Local\\Temp\\tmpoi_65ss4', '--quiet', '--find-links', 'https://github.com/thann/install_freedesktop/tarball/master#egg=install_freedesktop-0.2.0', 'install_freedesktop>=0.2.0']' returned non-zero exit status 1.
    ----------------------------------------
WARNING: Discarding git+git://github.com/thann/play-with-mpv. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

D:\Dowanloads\play-with-mpv-master\play-with-mpv-master>
```

If I try to install locally with `python setup.py install` I get:

```
D:\Dowanloads\play-with-mpv-master\play-with-mpv-master>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
```

Please advise. I have already installed setuptools.

**Comment by beew** [comment]
pip install setuptools wheel
