### ISSUE TITLE
Cannot run this command: pip install git+git://github.com/thann/play-with-mpv --user

### ISSUE THREAD

**Issue by zhouxiang19910319** [Thann/play-with-mpv#70]
Here is the error message.

```
zzrot@ASUS-X571GT-VX60GT:~$ pip install git+git://github.com/thann/play-with-mpv --user
Collecting git+git://github.com/thann/play-with-mpv
  Cloning git://github.com/thann/play-with-mpv to /tmp/pip-req-build-goe5c_j3
  Running command git clone -q git://github.com/thann/play-with-mpv /tmp/pip-req-build-goe5c_j3
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-goe5c_j3/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-goe5c_j3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-goe5c_j3/pip-egg-info
         cwd: /tmp/pip-req-build-goe5c_j3/
    Complete output (77 lines):
    ERROR: Exception:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
        status = self.run(options, args)
      File "/usr/lib/python3/dist-packages/pip/_internal/commands/wheel.py", line 161, in run
        resolver.resolve(requirement_set)
      File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
        discovered_reqs.extend(self._resolve_one(requirement_set, req))
      File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
        abstract_dist = self._get_abstract_dist_for(req_to_install)
      File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
        req.populate_link(self.finder, upgrade_allowed, require_hashes)
      File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 249, in populate_link
        self.link = finder.find_requirement(self, upgrade)
      File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 898, in find_requirement
        best_candidate_result = self.find_best_candidate(
      File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 881, in find_best_candidate
        candidates = self.find_all_candidates(project_name)
      File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 825, in find_all_candidates
        package_links = self.process_project_url(
      File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 790, in process_project_url
        html_page = self._link_collector.fetch_page(project_url)
      File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 497, in fetch_page
        return _get_html_page(location, session=self.session)
      File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 337, in _get_html_page
        resp = _get_html_response(url, session=session)
      File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 126, in _get_html_response
        resp = session.get(
      File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "/usr/lib/python3/dist-packages/pip/_internal/network/session.py", line 405, in request
        return super(PipSession, self).request(method, url, *args, **kwargs)
      File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/adapter.py", line 53, in send
        resp = super(CacheControlAdapter, self).send(request, **kw)
      File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/adapters.py", line 412, in send
        conn = self.get_connection(request.url, proxies)
      File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/adapters.py", line 309, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/adapters.py", line 182, in proxy_manager_for
        manager = self.proxy_manager[proxy] = SOCKSProxyManager(
      File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/adapters.py", line 47, in SOCKSProxyManager
        raise InvalidSchema("Missing dependencies for SOCKS support.")
    requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp0vfav_r3', '--quiet', '--find-links', 'https://github.com/thann/install_freedesktop/tarball/master#egg=install_freedesktop-0.2.0', 'install_freedesktop>=0.2.0']' returned non-zero exit status 2.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-goe5c_j3/setup.py", line 27, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 718, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/lib/python3/dist-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp0vfav_r3', '--quiet', '--find-links', 'https://github.com/thann/install_freedesktop/tarball/master#egg=install_freedesktop-0.2.0', 'install_freedesktop>=0.2.0']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
I am using Ubuntu 20.04 with V2Ray client and using custom HTTP and SOCKS5 ports. If it helps.

**Comment by adithya-r-prabhu** [comment]
Try installing "wheel" package using pip (`pip install wheel` or` pip3 install wheel`)

similar to https://github.com/Thann/play-with-mpv/issues/39

**Comment by Thann** [comment]
```
     raise InvalidSchema("Missing dependencies for SOCKS support.")
    requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
```
Its seems SOCKS and PIP don't play nice :thinking:
