### ISSUE TITLE
play-with-mpv-git(AUR) broke after updating to python3.10

### ISSUE THREAD

**Issue by cv1618** [Thann/play-with-mpv#74]
After I did an update on Arch and python updated from 3.9 to 3.10 play-with-mpv-git(aur) broke. When I run it in the terminal this is the output:

$ play-with-mpv
Traceback (most recent call last):
  File "/usr/bin/play-with-mpv", line 33, in <module>
    sys.exit(load_entry_point('play-with-mpv==0.1.0.post9+g07a9c1d', 'gui_scripts', 'play-with-mpv')())
  File "/usr/bin/play-with-mpv", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for play-with-mpv

**Comment by thegreatyellow67** [comment]
Same error in my Arch Linux system:
Traceback (most recent call last):
  File "/usr/bin/play-with-mpv", line 33, in <module>
    sys.exit(load_entry_point('play-with-mpv==0.1.0.post9+g07a9c1d', 'gui_scripts', 'play-with-mpv')())
  File "/usr/bin/play-with-mpv", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for play-with-mpv

**Comment by thegreatyellow67** [comment]
A suggestion for cv1618...

Try to download git source from:

https://aur.archlinux.org/play-with-mpv-git.git

then reinstall with:

makepkg -si

in my case problem has gone!

**Comment by jtraub** [comment]
When Python is updated to the new major release you need to rebuild your AUR packages that depend on Python.

See https://www.reddit.com/r/archlinux/comments/rf6c84/psa_python_310_is_in_core_rebuild_your_aur/ for example
