### ISSUE TITLE
issue can't install ?

### ISSUE THREAD

**Issue by omaru-ok** [Thann/play-with-mpv#86]
![image](https://user-images.githubusercontent.com/108952834/188506281-76de930e-a2f4-4167-8224-1a042aca423a.png)
idk anything

**Comment by nattymcfly5** [comment]
Im getting a similar error with Fedora 36

**Comment by omaru-ok** [comment]
> Im getting a similar error with Fedora 36

wath to do bro?

**Comment by nattymcfly5** [comment]
I just ran it again and it worked, idk why

**Comment by omaru-ok** [comment]
> I just ran it again and it worked, I ran this instead pip install git+https://github.com/thann/play-with-mpv --user
> 
> turns out git+git is depreciated

still error 

`❯ pip install git+https://github.com/thann/play-with-mpv --user
Collecting git+https://github.com/thann/play-with-mpv
  Cloning https://github.com/thann/play-with-mpv to c:\users\oma\appdata\local\temp\pip-req-build-odt0i8u3
  Running command git clone --filter=blob:none --quiet https://github.com/thann/play-with-mpv 'C:\Users\oma\AppData\Local\Temp\pip-req-build-odt0i8u3'
  Resolved https://github.com/thann/play-with-mpv to commit 07a9c1dd57d9e16538991b13fd3e2ed54d6e3a2d
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      C:\Users\oma\scoop\apps\python\current\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      WARNING: Skipping page https://github.com/thann/install_freedesktop/tarball/master#egg=install_freedesktop-0.2.0 because the GET request got Content-Type: application/x-gzip. The only supported Content-Types are application/vnd.pypi.simple.v1+json, application/vnd.pypi.simple.v1+html, and text/html
        WARNING: Cache entry deserialization failed, entry ignored
        error: subprocess-exited-with-error

        python setup.py bdist_wheel did not run successfully.
        exit code: 1

        [6 lines of output]
        usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
           or: setup.py --help [cmd1 cmd2 ...]
           or: setup.py --help-commands
           or: setup.py cmd --help

        error: invalid command 'bdist_wheel'
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for install_freedesktop
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "C:\Users\oma\scoop\apps\python\current\lib\site-packages\setuptools\installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "C:\Users\oma\scoop\apps\python\current\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\oma\\scoop\\apps\\python\\current\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\oma\\AppData\\Local\\Temp\\tmpe41ckh6j', '--quiet', '--find-links', 'https://github.com/thann/install_freedesktop/tarball/master#egg=install_freedesktop-0.2.0', 'install_freedesktop>=0.2.0']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\oma\AppData\Local\Temp\pip-req-build-odt0i8u3\setup.py", line 27, in <module>
          setup(
        File "C:\Users\oma\scoop\apps\python\current\lib\site-packages\setuptools\__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "C:\Users\oma\scoop\apps\python\current\lib\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\Users\oma\scoop\apps\python\current\lib\site-packages\setuptools\dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "C:\Users\oma\scoop\apps\python\current\lib\site-packages\pkg_resources\__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "C:\Users\oma\scoop\apps\python\current\lib\site-packages\pkg_resources\__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "C:\Users\oma\scoop\apps\python\current\lib\site-packages\pkg_resources\__init__.py", line 1087, in obtain
          return installer(requirement)
        File "C:\Users\oma\scoop\apps\python\current\lib\site-packages\setuptools\dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "C:\Users\oma\scoop\apps\python\current\lib\site-packages\setuptools\installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['C:\\Users\\oma\\scoop\\apps\\python\\current\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\oma\\AppData\\Local\\Temp\\tmpe41ckh6j', '--quiet', '--find-links', 'https://github.com/thann/install_freedesktop/tarball/master#egg=install_freedesktop-0.2.0', 'install_freedesktop>=0.2.0']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by tunaflsh** [comment]
I have exactly the same problems

**Comment by omaru-ok** [comment]
> I have exactly the same problems

owner is  sleeping :(

**Comment by shssoichiro** [comment]
@omaru-ok if you read the error message, when you try it with `https://` instead of `git://` it gives a different error. You need to `pip install --user wheel` then run `pip install git+https://github.com/thann/play-with-mpv --user` again.

**Comment by omaru-ok** [comment]
> pip install --user wheel

what does wheel means?

**Comment by omaru-ok** [comment]
> pip install git+https://github.com/thann/play-with-mpv --user

omg it does work :O

**Comment by rakkibhai** [comment]
$ pip install git+https://github.com/thann/play-with-mpv --user  
Collecting git+https://github.com/thann/play-with-mpv
  Cloning https://github.com/thann/play-with-mpv to /tmp/pip-req-build-fykxrl5c
  Running command git clone --filter=blob:none --quiet https://github.com/thann/play-with-mpv /tmp/pip-req-build-fykxrl5c
  Resolved https://github.com/thann/play-with-mpv to commit 07a9c1dd57d9e16538991b13fd3e2ed54d6e3a2d
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-fykxrl5c/setup.py", line 27, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 85, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 879, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 815, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 844, in _resolve_dist
          env = Environment(self.entries)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1044, in __init__
          self.scan(search_path)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1077, in scan
          self.add(dist)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1096, in add
          dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in hashcmp
          self.parsed_version,
          ^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2679, in parsed_version
          self._parsed_version = parse_version(self.version)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.4-py1'
      (package: adns)
      
              It is possible a package already installed in your system
              contains an version that is invalid according to PEP 440.
              You can try `pip install --use-pep517` as a workaround for this problem,
              or rely on a new virtual environment.
      
              If the problem refers to a package that is not installed yet,
              please contact that package's maintainers or distributors.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
                                       
kindly help. i am using kali 2023
